// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: city.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCity = `-- name: CreateCity :one
INSERT INTO cities (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateCity(ctx context.Context, name string) (City, error) {
	row := q.db.QueryRowContext(ctx, createCity, name)
	var i City
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteCity = `-- name: DeleteCity :exec
DELETE FROM cities
WHERE id = $1
`

func (q *Queries) DeleteCity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCity, id)
	return err
}

const getCityByID = `-- name: GetCityByID :one
SELECT id, name, created_at
FROM cities
WHERE id = $1
`

func (q *Queries) GetCityByID(ctx context.Context, id uuid.UUID) (City, error) {
	row := q.db.QueryRowContext(ctx, getCityByID, id)
	var i City
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const updateCity = `-- name: UpdateCity :one
UPDATE cities
SET name = $2
WHERE id = $1
RETURNING id, name, created_at
`

type UpdateCityParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateCity(ctx context.Context, arg UpdateCityParams) (City, error) {
	row := q.db.QueryRowContext(ctx, updateCity, arg.ID, arg.Name)
	var i City
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
