// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: entrepreneur.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEntrepreneur = `-- name: CreateEntrepreneur :one
INSERT INTO entrepreneurs (
    inn_id, legal_name, registration_authority, registration_date,
    registration_number, legal_form, ifut_code, dbibt_code,
    activity_status, charter_fund, founders, email,
    phone, mhobt_code, address, director_name
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, inn_id, legal_name, registration_authority, registration_date,
    registration_number, legal_form, ifut_code, dbibt_code,
    activity_status, charter_fund, founders, email,
    phone, mhobt_code, address, director_name, created_at
`

type CreateEntrepreneurParams struct {
	InnID                 uuid.UUID
	LegalName             string
	RegistrationAuthority string
	RegistrationDate      string
	RegistrationNumber    string
	LegalForm             string
	IfutCode              int32
	DbibtCode             int32
	ActivityStatus        bool
	CharterFund           int32
	Founders              string
	Email                 string
	Phone                 string
	MhobtCode             string
	Address               string
	DirectorName          string
}

func (q *Queries) CreateEntrepreneur(ctx context.Context, arg CreateEntrepreneurParams) (Entrepreneur, error) {
	row := q.db.QueryRowContext(ctx, createEntrepreneur,
		arg.InnID,
		arg.LegalName,
		arg.RegistrationAuthority,
		arg.RegistrationDate,
		arg.RegistrationNumber,
		arg.LegalForm,
		arg.IfutCode,
		arg.DbibtCode,
		arg.ActivityStatus,
		arg.CharterFund,
		arg.Founders,
		arg.Email,
		arg.Phone,
		arg.MhobtCode,
		arg.Address,
		arg.DirectorName,
	)
	var i Entrepreneur
	err := row.Scan(
		&i.ID,
		&i.InnID,
		&i.LegalName,
		&i.RegistrationAuthority,
		&i.RegistrationDate,
		&i.RegistrationNumber,
		&i.LegalForm,
		&i.IfutCode,
		&i.DbibtCode,
		&i.ActivityStatus,
		&i.CharterFund,
		&i.Founders,
		&i.Email,
		&i.Phone,
		&i.MhobtCode,
		&i.Address,
		&i.DirectorName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEntrepreneur = `-- name: DeleteEntrepreneur :exec
DELETE FROM entrepreneurs
WHERE id = $1
`

func (q *Queries) DeleteEntrepreneur(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEntrepreneur, id)
	return err
}

const getEntrepreneurByID = `-- name: GetEntrepreneurByID :one
SELECT e.id, e.inn_id, i.name as inn_name, e.legal_name, e.registration_authority,
    e.registration_date, e.registration_number, e.legal_form, e.ifut_code,
    e.dbibt_code, e.activity_status, e.charter_fund, e.founders, e.email,
    e.phone, e.mhobt_code, e.address, e.director_name, e.created_at
FROM entrepreneurs e
JOIN inns i ON e.inn_id = i.id
WHERE e.id = $1
`

type GetEntrepreneurByIDRow struct {
	ID                    uuid.UUID
	InnID                 uuid.UUID
	InnName               string
	LegalName             string
	RegistrationAuthority string
	RegistrationDate      string
	RegistrationNumber    string
	LegalForm             string
	IfutCode              int32
	DbibtCode             int32
	ActivityStatus        bool
	CharterFund           int32
	Founders              string
	Email                 string
	Phone                 string
	MhobtCode             string
	Address               string
	DirectorName          string
	CreatedAt             time.Time
}

func (q *Queries) GetEntrepreneurByID(ctx context.Context, id uuid.UUID) (GetEntrepreneurByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEntrepreneurByID, id)
	var i GetEntrepreneurByIDRow
	err := row.Scan(
		&i.ID,
		&i.InnID,
		&i.InnName,
		&i.LegalName,
		&i.RegistrationAuthority,
		&i.RegistrationDate,
		&i.RegistrationNumber,
		&i.LegalForm,
		&i.IfutCode,
		&i.DbibtCode,
		&i.ActivityStatus,
		&i.CharterFund,
		&i.Founders,
		&i.Email,
		&i.Phone,
		&i.MhobtCode,
		&i.Address,
		&i.DirectorName,
		&i.CreatedAt,
	)
	return i, err
}

const updateEntrepreneur = `-- name: UpdateEntrepreneur :one
UPDATE entrepreneurs
SET legal_name = $2,
    registration_authority = $3,
    registration_date = $4,
    registration_number = $5,
    legal_form = $6,
    ifut_code = $7,
    dbibt_code = $8,
    activity_status = $9,
    charter_fund = $10,
    founders = $11,
    email = $12,
    phone = $13,
    mhobt_code = $14,
    address = $15,
    director_name = $16
WHERE id = $1
RETURNING id, inn_id, legal_name, registration_authority, registration_date,
    registration_number, legal_form, ifut_code, dbibt_code,
    activity_status, charter_fund, founders, email,
    phone, mhobt_code, address, director_name, created_at
`

type UpdateEntrepreneurParams struct {
	ID                    uuid.UUID
	LegalName             string
	RegistrationAuthority string
	RegistrationDate      string
	RegistrationNumber    string
	LegalForm             string
	IfutCode              int32
	DbibtCode             int32
	ActivityStatus        bool
	CharterFund           int32
	Founders              string
	Email                 string
	Phone                 string
	MhobtCode             string
	Address               string
	DirectorName          string
}

func (q *Queries) UpdateEntrepreneur(ctx context.Context, arg UpdateEntrepreneurParams) (Entrepreneur, error) {
	row := q.db.QueryRowContext(ctx, updateEntrepreneur,
		arg.ID,
		arg.LegalName,
		arg.RegistrationAuthority,
		arg.RegistrationDate,
		arg.RegistrationNumber,
		arg.LegalForm,
		arg.IfutCode,
		arg.DbibtCode,
		arg.ActivityStatus,
		arg.CharterFund,
		arg.Founders,
		arg.Email,
		arg.Phone,
		arg.MhobtCode,
		arg.Address,
		arg.DirectorName,
	)
	var i Entrepreneur
	err := row.Scan(
		&i.ID,
		&i.InnID,
		&i.LegalName,
		&i.RegistrationAuthority,
		&i.RegistrationDate,
		&i.RegistrationNumber,
		&i.LegalForm,
		&i.IfutCode,
		&i.DbibtCode,
		&i.ActivityStatus,
		&i.CharterFund,
		&i.Founders,
		&i.Email,
		&i.Phone,
		&i.MhobtCode,
		&i.Address,
		&i.DirectorName,
		&i.CreatedAt,
	)
	return i, err
}
