// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: entrepreneur.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createEntrepreneur = `-- name: CreateEntrepreneur :one
INSERT INTO entrepreneurs (
    inn_id, legal_name, registration_authority, registration_date,
    registration_number, legal_form, ifut_code_id, dbibt_code,
    activity_status, charter_fund, founders, email,
    phone, mhobt_code, address, director_name, sqb_api_error
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, inn_id, legal_name, registration_authority, registration_date,
    registration_number, legal_form, ifut_code_id, dbibt_code,
    activity_status, charter_fund, founders, email,
    phone, mhobt_code, address, director_name, sqb_api_error, created_at
`

type CreateEntrepreneurParams struct {
	InnID                 uuid.UUID
	LegalName             string
	RegistrationAuthority string
	RegistrationDate      string
	RegistrationNumber    string
	LegalForm             string
	IfutCodeID            uuid.NullUUID
	DbibtCode             int32
	ActivityStatus        bool
	CharterFund           int32
	Founders              string
	Email                 string
	Phone                 string
	MhobtCode             string
	Address               string
	DirectorName          string
	SqbApiError           sql.NullString
}

type CreateEntrepreneurRow struct {
	ID                    uuid.UUID
	InnID                 uuid.UUID
	LegalName             string
	RegistrationAuthority string
	RegistrationDate      string
	RegistrationNumber    string
	LegalForm             string
	IfutCodeID            uuid.NullUUID
	DbibtCode             int32
	ActivityStatus        bool
	CharterFund           int32
	Founders              string
	Email                 string
	Phone                 string
	MhobtCode             string
	Address               string
	DirectorName          string
	SqbApiError           sql.NullString
	CreatedAt             time.Time
}

func (q *Queries) CreateEntrepreneur(ctx context.Context, arg CreateEntrepreneurParams) (CreateEntrepreneurRow, error) {
	row := q.db.QueryRowContext(ctx, createEntrepreneur,
		arg.InnID,
		arg.LegalName,
		arg.RegistrationAuthority,
		arg.RegistrationDate,
		arg.RegistrationNumber,
		arg.LegalForm,
		arg.IfutCodeID,
		arg.DbibtCode,
		arg.ActivityStatus,
		arg.CharterFund,
		arg.Founders,
		arg.Email,
		arg.Phone,
		arg.MhobtCode,
		arg.Address,
		arg.DirectorName,
		arg.SqbApiError,
	)
	var i CreateEntrepreneurRow
	err := row.Scan(
		&i.ID,
		&i.InnID,
		&i.LegalName,
		&i.RegistrationAuthority,
		&i.RegistrationDate,
		&i.RegistrationNumber,
		&i.LegalForm,
		&i.IfutCodeID,
		&i.DbibtCode,
		&i.ActivityStatus,
		&i.CharterFund,
		&i.Founders,
		&i.Email,
		&i.Phone,
		&i.MhobtCode,
		&i.Address,
		&i.DirectorName,
		&i.SqbApiError,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEntrepreneur = `-- name: DeleteEntrepreneur :exec
DELETE FROM entrepreneurs
WHERE id = $1
`

func (q *Queries) DeleteEntrepreneur(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEntrepreneur, id)
	return err
}

const getEntrepreneurByID = `-- name: GetEntrepreneurByID :one
SELECT e.id, e.inn_id, i.name as inn_name, e.legal_name, e.registration_authority,
    e.registration_date, e.registration_number, e.legal_form, e.ifut_code_id,
    ic.name as ifut_code_name, e.dbibt_code, e.activity_status, e.charter_fund,
    e.founders, e.email, e.phone, e.mhobt_code, e.address, e.director_name,
    e.sqb_api_error, e.created_at
FROM entrepreneurs e
JOIN inns i ON e.inn_id = i.id
LEFT JOIN ifut_codes ic ON e.ifut_code_id = ic.id
WHERE e.id = $1
`

type GetEntrepreneurByIDRow struct {
	ID                    uuid.UUID
	InnID                 uuid.UUID
	InnName               string
	LegalName             string
	RegistrationAuthority string
	RegistrationDate      string
	RegistrationNumber    string
	LegalForm             string
	IfutCodeID            uuid.NullUUID
	IfutCodeName          sql.NullString
	DbibtCode             int32
	ActivityStatus        bool
	CharterFund           int32
	Founders              string
	Email                 string
	Phone                 string
	MhobtCode             string
	Address               string
	DirectorName          string
	SqbApiError           sql.NullString
	CreatedAt             time.Time
}

func (q *Queries) GetEntrepreneurByID(ctx context.Context, id uuid.UUID) (GetEntrepreneurByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEntrepreneurByID, id)
	var i GetEntrepreneurByIDRow
	err := row.Scan(
		&i.ID,
		&i.InnID,
		&i.InnName,
		&i.LegalName,
		&i.RegistrationAuthority,
		&i.RegistrationDate,
		&i.RegistrationNumber,
		&i.LegalForm,
		&i.IfutCodeID,
		&i.IfutCodeName,
		&i.DbibtCode,
		&i.ActivityStatus,
		&i.CharterFund,
		&i.Founders,
		&i.Email,
		&i.Phone,
		&i.MhobtCode,
		&i.Address,
		&i.DirectorName,
		&i.SqbApiError,
		&i.CreatedAt,
	)
	return i, err
}

const setSqbApiError = `-- name: SetSqbApiError :exec
UPDATE entrepreneurs
SET sqb_api_error = $2
WHERE id = $1
`

type SetSqbApiErrorParams struct {
	ID          uuid.UUID
	SqbApiError sql.NullString
}

func (q *Queries) SetSqbApiError(ctx context.Context, arg SetSqbApiErrorParams) error {
	_, err := q.db.ExecContext(ctx, setSqbApiError, arg.ID, arg.SqbApiError)
	return err
}

const updateEntrepreneur = `-- name: UpdateEntrepreneur :one
UPDATE entrepreneurs
SET legal_name = $2,
    registration_authority = $3,
    registration_date = $4,
    registration_number = $5,
    legal_form = $6,
    ifut_code_id = $7,
    dbibt_code = $8,
    activity_status = $9,
    charter_fund = $10,
    founders = $11,
    email = $12,
    phone = $13,
    mhobt_code = $14,
    address = $15,
    director_name = $16
WHERE id = $1
RETURNING id, inn_id, legal_name, registration_authority, registration_date,
    registration_number, legal_form, ifut_code_id, dbibt_code,
    activity_status, charter_fund, founders, email,
    phone, mhobt_code, address, director_name, sqb_api_error, created_at
`

type UpdateEntrepreneurParams struct {
	ID                    uuid.UUID
	LegalName             string
	RegistrationAuthority string
	RegistrationDate      string
	RegistrationNumber    string
	LegalForm             string
	IfutCodeID            uuid.NullUUID
	DbibtCode             int32
	ActivityStatus        bool
	CharterFund           int32
	Founders              string
	Email                 string
	Phone                 string
	MhobtCode             string
	Address               string
	DirectorName          string
}

type UpdateEntrepreneurRow struct {
	ID                    uuid.UUID
	InnID                 uuid.UUID
	LegalName             string
	RegistrationAuthority string
	RegistrationDate      string
	RegistrationNumber    string
	LegalForm             string
	IfutCodeID            uuid.NullUUID
	DbibtCode             int32
	ActivityStatus        bool
	CharterFund           int32
	Founders              string
	Email                 string
	Phone                 string
	MhobtCode             string
	Address               string
	DirectorName          string
	SqbApiError           sql.NullString
	CreatedAt             time.Time
}

func (q *Queries) UpdateEntrepreneur(ctx context.Context, arg UpdateEntrepreneurParams) (UpdateEntrepreneurRow, error) {
	row := q.db.QueryRowContext(ctx, updateEntrepreneur,
		arg.ID,
		arg.LegalName,
		arg.RegistrationAuthority,
		arg.RegistrationDate,
		arg.RegistrationNumber,
		arg.LegalForm,
		arg.IfutCodeID,
		arg.DbibtCode,
		arg.ActivityStatus,
		arg.CharterFund,
		arg.Founders,
		arg.Email,
		arg.Phone,
		arg.MhobtCode,
		arg.Address,
		arg.DirectorName,
	)
	var i UpdateEntrepreneurRow
	err := row.Scan(
		&i.ID,
		&i.InnID,
		&i.LegalName,
		&i.RegistrationAuthority,
		&i.RegistrationDate,
		&i.RegistrationNumber,
		&i.LegalForm,
		&i.IfutCodeID,
		&i.DbibtCode,
		&i.ActivityStatus,
		&i.CharterFund,
		&i.Founders,
		&i.Email,
		&i.Phone,
		&i.MhobtCode,
		&i.Address,
		&i.DirectorName,
		&i.SqbApiError,
		&i.CreatedAt,
	)
	return i, err
}
