// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ifut_code.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createIfutCode = `-- name: CreateIfutCode :one
INSERT INTO ifut_codes (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateIfutCode(ctx context.Context, name string) (IfutCode, error) {
	row := q.db.QueryRowContext(ctx, createIfutCode, name)
	var i IfutCode
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getIfutCodeByID = `-- name: GetIfutCodeByID :one
SELECT id, name, created_at
FROM ifut_codes
WHERE id = $1
`

func (q *Queries) GetIfutCodeByID(ctx context.Context, id uuid.UUID) (IfutCode, error) {
	row := q.db.QueryRowContext(ctx, getIfutCodeByID, id)
	var i IfutCode
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getIfutCodeByName = `-- name: GetIfutCodeByName :one
SELECT id, name, created_at
FROM ifut_codes
WHERE name = $1
`

func (q *Queries) GetIfutCodeByName(ctx context.Context, name string) (IfutCode, error) {
	row := q.db.QueryRowContext(ctx, getIfutCodeByName, name)
	var i IfutCode
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
