// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: inn.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createINN = `-- name: CreateINN :one
INSERT INTO inns (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateINN(ctx context.Context, name string) (Inn, error) {
	row := q.db.QueryRowContext(ctx, createINN, name)
	var i Inn
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getINNByID = `-- name: GetINNByID :one
SELECT id, name, created_at
FROM inns
WHERE id = $1
`

func (q *Queries) GetINNByID(ctx context.Context, id uuid.UUID) (Inn, error) {
	row := q.db.QueryRowContext(ctx, getINNByID, id)
	var i Inn
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getINNByName = `-- name: GetINNByName :one
SELECT id, name, created_at
FROM inns
WHERE name = $1
`

func (q *Queries) GetINNByName(ctx context.Context, name string) (Inn, error) {
	row := q.db.QueryRowContext(ctx, getINNByName, name)
	var i Inn
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
