// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type City struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type Entrepreneur struct {
	ID                    uuid.UUID
	InnID                 uuid.UUID
	LegalName             string
	RegistrationAuthority string
	RegistrationDate      string
	RegistrationNumber    string
	LegalForm             string
	DbibtCode             int32
	ActivityStatus        bool
	CharterFund           int32
	Founders              string
	Email                 string
	Phone                 string
	MhobtCode             string
	Address               string
	DirectorName          string
	CreatedAt             time.Time
	IfutCodeID            uuid.NullUUID
	SqbApiError           sql.NullString
}

type IfutCode struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type Inn struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type SyncerState struct {
	Key       string
	Value     string
	UpdatedAt sql.NullTime
}

type User struct {
	ID           uuid.UUID
	FullName     string
	Role         string
	Login        string
	PasswordHash string
	Status       bool
	CreatedAt    time.Time
}

type UserActiveSession struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	DeviceID         string
	RefreshTokenHash string
	LastLoginAt      time.Time
	CreatedAt        time.Time
}
