// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID           uuid.UUID
	FullName     string
	Role         string
	Login        string
	PasswordHash string
	Status       bool
	CreatedAt    time.Time
}

type UserActiveSession struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	DeviceID         string
	RefreshTokenHash string
	LastLoginAt      time.Time
	CreatedAt        time.Time
}
