// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO user_active_sessions (user_id, device_id, refresh_token_hash, last_login_at)
VALUES ($1, $2, $3, NOW())
RETURNING id, user_id, device_id, refresh_token_hash, last_login_at, created_at
`

type CreateSessionParams struct {
	UserID           uuid.UUID
	DeviceID         string
	RefreshTokenHash string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserActiveSession, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.UserID, arg.DeviceID, arg.RefreshTokenHash)
	var i UserActiveSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.RefreshTokenHash,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM user_active_sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM user_active_sessions
WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUserID, userID)
	return err
}

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT id, user_id, device_id, refresh_token_hash, last_login_at, created_at
FROM user_active_sessions
WHERE refresh_token_hash = $1
`

func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (UserActiveSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByRefreshTokenHash, refreshTokenHash)
	var i UserActiveSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.RefreshTokenHash,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByUserAndDevice = `-- name: GetSessionByUserAndDevice :one
SELECT id, user_id, device_id, refresh_token_hash, last_login_at, created_at
FROM user_active_sessions
WHERE user_id = $1 AND device_id = $2
`

type GetSessionByUserAndDeviceParams struct {
	UserID   uuid.UUID
	DeviceID string
}

func (q *Queries) GetSessionByUserAndDevice(ctx context.Context, arg GetSessionByUserAndDeviceParams) (UserActiveSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByUserAndDevice, arg.UserID, arg.DeviceID)
	var i UserActiveSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.RefreshTokenHash,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionToken = `-- name: UpdateSessionToken :one
UPDATE user_active_sessions
SET refresh_token_hash = $2, last_login_at = NOW()
WHERE id = $1
RETURNING id, user_id, device_id, refresh_token_hash, last_login_at, created_at
`

type UpdateSessionTokenParams struct {
	ID               uuid.UUID
	RefreshTokenHash string
}

func (q *Queries) UpdateSessionToken(ctx context.Context, arg UpdateSessionTokenParams) (UserActiveSession, error) {
	row := q.db.QueryRowContext(ctx, updateSessionToken, arg.ID, arg.RefreshTokenHash)
	var i UserActiveSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.RefreshTokenHash,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}
