// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (full_name, role, login, password_hash, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, full_name, role, login, password_hash, status, created_at
`

type CreateUserParams struct {
	FullName     string
	Role         string
	Login        string
	PasswordHash string
	Status       bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FullName,
		arg.Role,
		arg.Login,
		arg.PasswordHash,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Role,
		&i.Login,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, role, login, password_hash, status, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Role,
		&i.Login,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, full_name, role, login, password_hash, status, created_at
FROM users
WHERE login = $1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Role,
		&i.Login,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET full_name = $2, role = $3, status = $4
WHERE id = $1
RETURNING id, full_name, role, login, password_hash, status, created_at
`

type UpdateUserParams struct {
	ID       uuid.UUID
	FullName string
	Role     string
	Status   bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.Role,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Role,
		&i.Login,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
